In [1]:
import pandas as pd

In [2]:
# 1.データの読み込み
## weather.csvを読み込み、dfで定義してください

In [3]:
df= pd.read_csv("./data/weather.csv")
df

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1
3,2019/12/16,6.9,8,1,12.5,8,1,1.3,8,1,...,1,NaN,0,1,1.1,8,1,8.9,8,1
4,2019/12/17,8.2,8,1,10.3,8,1,5.7,8,1,...,1,NaN,0,1,1.1,8,1,0.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

In [4]:
# 2.データの中身確認
## 読み込んだデータdfの先頭3行、末尾10行を表示してください。

In [5]:
df.head(3)

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1

In [6]:
df.tail(10)

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
358,2020/12/5,6.0,8,1,7.3,8,1,4.3,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
359,2020/12/6,8.0,8,1,13.3,8,1,4.5,8,1,...,1,NaN,0,1,1.0,8,1,3.8,8,1
360,2020/12/7,9.0,8,1,16.0,8,1,4.2,8,1,...,1,NaN,0,1,0.7,8,1,9.0,8,1
361,2020/12/8,10.4,8,1,16.0,8,1,4.6,8,1,...,1,NaN,0,1,1.3,8,1,6.9,8,1
362,2020/12/9,9.2,8,1,11.2,8,1,8.3,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

In [7]:
# 3.不要な列、行の削除
## 先頭行と、カラム名（列名）が「〇〇.1」「〇〇.2」となっているものを削除したDataFrame dfを再定義してください。

In [8]:
columns_list = df.columns
columns_list

Index(['年月日', '平均気温(℃)', '平均気温(℃).1', '平均気温(℃).2', '最高気温(℃)', '最高気温(℃).1',
       '最高気温(℃).2', '最低気温(℃)', '最低気温(℃).1', '最低気温(℃).2', '降水量の合計(mm)',
       '降水量の合計(mm).1', '降水量の合計(mm).2', '最深積雪(cm)', '最深積雪(cm).1', '最深積雪(cm).2',
       '平均雲量(10分比)', '平均雲量(10分比).1', '平均雲量(10分比).2', '平均蒸気圧(hPa)',
       '平均蒸気圧(hPa).1', '平均蒸気圧(hPa).2', '平均風速(m/s)', '平均風速(m/s).1',
       '平均風速(m/s).2', '日照時間(時間)', '日照時間(時間).1', '日照時間(時間).2'],
      dtype='object')

In [9]:
### ".1"か".2"で終わるものを除外する（filterをつかう？）

In [10]:
target_columns_list = list(filter(lambda column: not(column.endswith(".1") or column.endswith(".2")), columns_list))
target_columns_list

['年月日',
 '平均気温(℃)',
 '最高気温(℃)',
 '最低気温(℃)',
 '降水量の合計(mm)',
 '最深積雪(cm)',
 '平均雲量(10分比)',
 '平均蒸気圧(hPa)',
 '平均風速(m/s)',
 '日照時間(時間)']

In [11]:
df = df[target_columns_list][1:]
df

,年月日,平均気温(℃),最高気温(℃),最低気温(℃),降水量の合計(mm),最深積雪(cm),平均雲量(10分比),平均蒸気圧(hPa),平均風速(m/s),日照時間(時間)
1,2019/12/14,9.3,15.9,3.2,0.0,NaN,NaN,NaN,2.0,8.9
2,2019/12/15,7.8,11.1,4.0,0.0,NaN,NaN,NaN,2.3,6.3
3,2019/12/16,6.9,12.5,1.3,0.0,NaN,NaN,NaN,1.1,8.9
4,2019/12/17,8.2,10.3,5.7,2.0,NaN,NaN,NaN,1.1,0.2
5,2019/12/18,9.9,15.0,4.8,0.0,NaN,NaN,NaN,1.2,4.3
...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,11.1,6.0,0.5,NaN,NaN,NaN,1.4,0.0
364,2020/12/11,9.2,13.8,3.5,0.0,NaN,NaN,NaN,0.8,4.3
365,2020/12/12,10.4,14.0,8.0,0.0,NaN,NaN,NaN,1.4,1.4
366,2020/12/13,8.6,14.4,4.4,0.0,NaN,NaN,NaN,1.0,5.5
367,2020/12/14,7.8,12.2,4.4,0.0,NaN,NaN,NaN,1.9,4.4

In [12]:
## 答え合わせしたら手動で削除していた。自分はスマートにできてよかった。

In [13]:
# 4.データの型、サイズ、列名、行名の確認
## 下記の値を取得しなさい
## ・各列のデータ型
## ・DataFrameのサイズ
## ・列名
## ・行名

In [1]:
# test